# Form implementation generated from reading ui file 'editcustomer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class editCustomerDialog(object):
    def setupUi(self, editcustomer):
        editcustomer.setObjectName("editcustomer")
        editcustomer.resize(640, 324)
        editcustomer.setStyleSheet("background:rgb(72, 72, 72)")
        self.label_6 = QtWidgets.QLabel(parent=editcustomer)
        self.label_6.setGeometry(QtCore.QRect(70, 110, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.phonenumber = QtWidgets.QLineEdit(parent=editcustomer)
        self.phonenumber.setGeometry(QtCore.QRect(160, 130, 201, 22))
        self.phonenumber.setStyleSheet(" background: white")
        self.phonenumber.setObjectName("phonenumber")
        self.label_5 = QtWidgets.QLabel(parent=editcustomer)
        self.label_5.setGeometry(QtCore.QRect(370, 120, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.Confirm = QtWidgets.QPushButton(parent=editcustomer)
        self.Confirm.setGeometry(QtCore.QRect(100, 250, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Confirm.setFont(font)
        self.Confirm.setStyleSheet("QPushButton {\n"
"                background-color: rgb(6, 217, 66);\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(50, 255, 100);\n"
"            }")
        self.Confirm.setFlat(False)
        self.Confirm.setObjectName("Confirm")
        self.Cancel = QtWidgets.QPushButton(parent=editcustomer)
        self.Cancel.setGeometry(QtCore.QRect(340, 250, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel.setFont(font)
        self.Cancel.setStyleSheet("QPushButton {\n"
"                background-color: rgb(200, 46, 18);\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(255, 100, 100);\n"
"            }")
        self.Cancel.setObjectName("Cancel")
        self.namecustomer = QtWidgets.QLineEdit(parent=editcustomer)
        self.namecustomer.setGeometry(QtCore.QRect(160, 86, 411, 22))
        self.namecustomer.setStyleSheet(" background: white")
        self.namecustomer.setFrame(False)
        self.namecustomer.setObjectName("namecustomer")
        self.openpicbutton = QtWidgets.QPushButton(parent=editcustomer)
        self.openpicbutton.setGeometry(QtCore.QRect(160, 190, 411, 31))
        self.openpicbutton.setStyleSheet("QPushButton {\n"
"                                        background-color: rgb(72, 72, 72);\n"
"                                        color:rgb(255, 255, 255);\n"
"                                        border: none;\n"
"                                        padding: 10px;\n"
"                                        }\n"
"QPushButton:hover {\n"
"                                        background-color: rgb(100, 100, 100);\n"
"                                        }")
        self.openpicbutton.setObjectName("openpicbutton")
        self.label_4 = QtWidgets.QLabel(parent=editcustomer)
        self.label_4.setGeometry(QtCore.QRect(99, 81, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(parent=editcustomer)
        self.label_9.setGeometry(QtCore.QRect(40, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(parent=editcustomer)
        self.comboBox.setGeometry(QtCore.QRect(450, 130, 121, 22))
        self.comboBox.setStyleSheet("background-color:white")
        self.comboBox.setObjectName("comboBox")
        self.frame = QtWidgets.QFrame(parent=editcustomer)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(230, 0, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")

        self.retranslateUi(editcustomer)
        QtCore.QMetaObject.connectSlotsByName(editcustomer)

    def retranslateUi(self, editcustomer):
        _translate = QtCore.QCoreApplication.translate
        editcustomer.setWindowTitle(_translate("editcustomer", "Dialog"))
        self.label_6.setText(_translate("editcustomer", "Phone Number:"))
        self.label_5.setText(_translate("editcustomer", "Gender:"))
        self.Confirm.setText(_translate("editcustomer", "Confirm"))
        self.Cancel.setText(_translate("editcustomer", "Cancel"))
        self.openpicbutton.setText(_translate("editcustomer", "Select Picture"))
        self.label_4.setText(_translate("editcustomer", "Name:"))
        self.label_9.setText(_translate("editcustomer", "Valid ID Photo:"))
        self.label.setText(_translate("editcustomer", "Edit Customer"))
