# Form implementation generated from reading ui file 'returnbook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReturnDialog(object):
    def setupUi(self, ReturnDialog):
        ReturnDialog.setObjectName("ReturnDialog")
        ReturnDialog.resize(592, 334)
        ReturnDialog.setStyleSheet("background:rgb(72, 72, 72)")
        self.frame = QtWidgets.QFrame(parent=ReturnDialog)
        self.frame.setGeometry(QtCore.QRect(0, -6, 601, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(210, 10, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=ReturnDialog)
        self.label_6.setGeometry(QtCore.QRect(49, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=ReturnDialog)
        self.label_7.setGeometry(QtCore.QRect(79, 164, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.borrowedbook = QtWidgets.QComboBox(parent=ReturnDialog)
        self.borrowedbook.setGeometry(QtCore.QRect(180, 84, 371, 22))
        self.borrowedbook.setStyleSheet(" background: white")
        self.borrowedbook.setObjectName("borrowedbook")
        self.label_8 = QtWidgets.QLabel(parent=ReturnDialog)
        self.label_8.setGeometry(QtCore.QRect(340, 170, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.return_2 = QtWidgets.QPushButton(parent=ReturnDialog)
        self.return_2.setGeometry(QtCore.QRect(70, 270, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.return_2.setFont(font)
        self.return_2.setStyleSheet("QPushButton {\n"
"                background-color: rgb(6, 217, 66);\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(50, 255, 100);\n"
"            }")
        self.return_2.setFlat(False)
        self.return_2.setObjectName("return_2")
        self.label_4 = QtWidgets.QLabel(parent=ReturnDialog)
        self.label_4.setGeometry(QtCore.QRect(39, 79, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.rentfeefield = QtWidgets.QLineEdit(parent=ReturnDialog)
        self.rentfeefield.setEnabled(True)
        self.rentfeefield.setGeometry(QtCore.QRect(180, 216, 231, 22))
        self.rentfeefield.setStyleSheet(" background: white")
        self.rentfeefield.setFrame(False)
        self.rentfeefield.setObjectName("rentfeefield")
        self.Cancel = QtWidgets.QPushButton(parent=ReturnDialog)
        self.Cancel.setGeometry(QtCore.QRect(320, 270, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel.setFont(font)
        self.Cancel.setStyleSheet("QPushButton {\n"
"                background-color: rgb(200, 46, 18);\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(255, 100, 100);\n"
"            }")
        self.Cancel.setObjectName("Cancel")
        self.label_5 = QtWidgets.QLabel(parent=ReturnDialog)
        self.label_5.setGeometry(QtCore.QRect(80, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.customer = QtWidgets.QLineEdit(parent=ReturnDialog)
        self.customer.setGeometry(QtCore.QRect(180, 120, 371, 22))
        self.customer.setStyleSheet(" background: white")
        self.customer.setFrame(False)
        self.customer.setObjectName("customer")
        self.startlabel = QtWidgets.QLabel(parent=ReturnDialog)
        self.startlabel.setGeometry(QtCore.QRect(183, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.startlabel.setFont(font)
        self.startlabel.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"                color: white;")
        self.startlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.startlabel.setObjectName("startlabel")
        self.endlabel = QtWidgets.QLabel(parent=ReturnDialog)
        self.endlabel.setGeometry(QtCore.QRect(370, 169, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.endlabel.setFont(font)
        self.endlabel.setStyleSheet("background-color: rgb(76, 94, 255);\n"
"                color: white;")
        self.endlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.endlabel.setObjectName("endlabel")

        self.retranslateUi(ReturnDialog)
        QtCore.QMetaObject.connectSlotsByName(ReturnDialog)

    def retranslateUi(self, ReturnDialog):
        _translate = QtCore.QCoreApplication.translate
        ReturnDialog.setWindowTitle(_translate("ReturnDialog", "Return Book"))
        self.label.setText(_translate("ReturnDialog", "Return Book"))
        self.label_6.setText(_translate("ReturnDialog", "Overdue Fine:"))
        self.label_7.setText(_translate("ReturnDialog", "Rent Date:"))
        self.label_8.setText(_translate("ReturnDialog", "to"))
        self.return_2.setText(_translate("ReturnDialog", "Return"))
        self.label_4.setText(_translate("ReturnDialog", "Borrowed Book"))
        self.rentfeefield.setPlaceholderText(_translate("ReturnDialog", "No Overdue Fee"))
        self.Cancel.setText(_translate("ReturnDialog", "Cancel"))
        self.label_5.setText(_translate("ReturnDialog", "Customer:"))
        self.startlabel.setText(_translate("ReturnDialog", "Start Date"))
        self.endlabel.setText(_translate("ReturnDialog", "End Date"))
